#!/bin/bash

# Phantom Tunnel Interactive Setup Script
# This script guides you through setting up a server or client

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Print banner
print_banner() {
    echo -e "${CYAN}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║                                                           ║"
    echo "║              PHANTOM TUNNEL SETUP                         ║"
    echo "║         Secure, Censorship-Resistant Tunneling            ║"
    echo "║                                                           ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# Print step
step() {
    echo -e "${GREEN}==>${NC} $1"
}

# Print info
info() {
    echo -e "${BLUE}   $1${NC}"
}

# Print warning
warn() {
    echo -e "${YELLOW}Warning: $1${NC}"
}

# Print error
error() {
    echo -e "${RED}Error: $1${NC}"
}

# Check if binary exists
check_binary() {
    if [ ! -f "./target/release/phantom-$1" ]; then
        echo ""
        warn "Binary not found. Building now..."
        echo ""
        cargo build --release
    fi
}

# Generate keypair using the binary
generate_keypair() {
    local type=$1
    local output
    output=$(./target/release/phantom-$type --generate-key 2>&1)

    # Extract public and private keys from output
    PUBLIC_KEY=$(echo "$output" | grep -A1 "PUBLIC KEY" | tail -1 | tr -d ' ║')
    PRIVATE_KEY=$(echo "$output" | grep -A1 "PRIVATE KEY" | tail -1 | tr -d ' ║')
}

# Setup server
setup_server() {
    echo ""
    step "Server Setup"
    echo ""

    check_binary "server"

    # Get listen address
    echo -e "${CYAN}Enter the address and port to listen on${NC}"
    info "This is where clients will connect"
    info "Use 0.0.0.0 to listen on all interfaces"
    read -p "Listen address [0.0.0.0:443]: " LISTEN_ADDR
    LISTEN_ADDR=${LISTEN_ADDR:-"0.0.0.0:443"}
    echo ""

    # Get max connections
    read -p "Maximum concurrent connections [1000]: " MAX_CONN
    MAX_CONN=${MAX_CONN:-1000}
    echo ""

    # Generate keypair
    step "Generating server keypair..."
    generate_keypair "server"
    echo ""

    echo -e "${GREEN}Server Public Key (share this with clients):${NC}"
    echo -e "${YELLOW}$PUBLIC_KEY${NC}"
    echo ""

    # Ask about allowed clients
    echo -e "${CYAN}Do you want to add allowed client public keys now?${NC}"
    info "You can also add them later by editing the config file"
    read -p "Add client keys now? [y/N]: " ADD_CLIENTS

    ALLOWED_CLIENTS=""
    if [[ "$ADD_CLIENTS" =~ ^[Yy]$ ]]; then
        echo ""
        info "Enter client public keys one per line"
        info "Press Enter on empty line when done"
        echo ""
        while true; do
            read -p "Client public key (or Enter to finish): " CLIENT_KEY
            if [ -z "$CLIENT_KEY" ]; then
                break
            fi
            if [ -z "$ALLOWED_CLIENTS" ]; then
                ALLOWED_CLIENTS="    \"$CLIENT_KEY\""
            else
                ALLOWED_CLIENTS="$ALLOWED_CLIENTS,
    \"$CLIENT_KEY\""
            fi
        done
    fi

    # Config file path
    echo ""
    read -p "Config file path [server.toml]: " CONFIG_PATH
    CONFIG_PATH=${CONFIG_PATH:-"server.toml"}

    # Write config
    cat > "$CONFIG_PATH" << EOF
# Phantom Tunnel Server Configuration
# Generated by setup script

[server]
# Address to listen on
listen = "$LISTEN_ADDR"

# Server keypair (auto-generated)
private_key = "$PRIVATE_KEY"
public_key = "$PUBLIC_KEY"

# Allowed client public keys
# Add client public keys here to grant access
allowed_clients = [
$ALLOWED_CLIENTS
]

# Maximum concurrent connections
max_connections = $MAX_CONN

[logging]
level = "info"
format = "pretty"
EOF

    echo ""
    echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}Server setup complete!${NC}"
    echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "Config saved to: $CONFIG_PATH"
    echo ""
    echo -e "${YELLOW}IMPORTANT - Share this public key with your clients:${NC}"
    echo "$PUBLIC_KEY"
    echo ""
    echo "To start the server:"
    echo -e "  ${CYAN}./target/release/phantom-server -c $CONFIG_PATH${NC}"
    echo ""
}

# Setup client
setup_client() {
    echo ""
    step "Client Setup"
    echo ""

    check_binary "client"

    # Get server address
    echo -e "${CYAN}Enter the server address${NC}"
    info "Example: myserver.com:443 or 192.168.1.100:443"
    read -p "Server address: " SERVER_ADDR
    while [ -z "$SERVER_ADDR" ]; do
        error "Server address is required"
        read -p "Server address: " SERVER_ADDR
    done
    echo ""

    # Get server public key
    echo -e "${CYAN}Enter the server's public key${NC}"
    info "Get this from the server administrator"
    read -p "Server public key: " SERVER_PUBLIC_KEY
    while [ -z "$SERVER_PUBLIC_KEY" ]; do
        error "Server public key is required"
        read -p "Server public key: " SERVER_PUBLIC_KEY
    done
    echo ""

    # Generate client keypair
    step "Generating client keypair..."
    generate_keypair "client"
    echo ""

    echo -e "${GREEN}Client Public Key (share this with server admin):${NC}"
    echo -e "${YELLOW}$PUBLIC_KEY${NC}"
    echo ""

    # Proxy settings
    echo -e "${CYAN}Local proxy settings${NC}"
    read -p "SOCKS5 proxy address [127.0.0.1:1080]: " SOCKS5_ADDR
    SOCKS5_ADDR=${SOCKS5_ADDR:-"127.0.0.1:1080"}

    read -p "HTTP proxy address [127.0.0.1:8080]: " HTTP_ADDR
    HTTP_ADDR=${HTTP_ADDR:-"127.0.0.1:8080"}
    echo ""

    # TLS profile
    echo -e "${CYAN}TLS fingerprint profile${NC}"
    info "This makes your traffic look like a specific browser"
    echo "  1) chrome (recommended)"
    echo "  2) firefox"
    echo "  3) safari"
    echo "  4) random"
    read -p "Select profile [1]: " PROFILE_CHOICE
    case $PROFILE_CHOICE in
        2) TLS_PROFILE="firefox" ;;
        3) TLS_PROFILE="safari" ;;
        4) TLS_PROFILE="random" ;;
        *) TLS_PROFILE="chrome" ;;
    esac
    echo ""

    # Enable padding
    read -p "Enable traffic padding? (recommended for censored networks) [Y/n]: " ENABLE_PADDING
    if [[ "$ENABLE_PADDING" =~ ^[Nn]$ ]]; then
        PADDING="false"
    else
        PADDING="true"
    fi
    echo ""

    # Config file path
    read -p "Config file path [client.toml]: " CONFIG_PATH
    CONFIG_PATH=${CONFIG_PATH:-"client.toml"}

    # Write config
    cat > "$CONFIG_PATH" << EOF
# Phantom Tunnel Client Configuration
# Generated by setup script

[client]
# Server to connect to
server = "$SERVER_ADDR"

# Server's public key (required)
server_public_key = "$SERVER_PUBLIC_KEY"

# Client keypair (auto-generated)
private_key = "$PRIVATE_KEY"
public_key = "$PUBLIC_KEY"

# Local proxy addresses
socks5_listen = "$SOCKS5_ADDR"
http_listen = "$HTTP_ADDR"

# TLS fingerprint profile (chrome, firefox, safari, random)
tls_profile = "$TLS_PROFILE"

# Traffic padding (recommended for censored networks)
enable_padding = $PADDING

[logging]
level = "info"
format = "pretty"
EOF

    echo ""
    echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}Client setup complete!${NC}"
    echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "Config saved to: $CONFIG_PATH"
    echo ""
    echo -e "${YELLOW}IMPORTANT - Share this public key with server admin:${NC}"
    echo "$PUBLIC_KEY"
    echo ""
    echo "To start the client:"
    echo -e "  ${CYAN}./target/release/phantom-client -c $CONFIG_PATH${NC}"
    echo ""
    echo "Then configure your applications to use:"
    echo -e "  SOCKS5: ${CYAN}$SOCKS5_ADDR${NC}"
    echo -e "  HTTP:   ${CYAN}$HTTP_ADDR${NC}"
    echo ""
}

# Main menu
main() {
    print_banner

    echo "What would you like to set up?"
    echo ""
    echo "  1) Server - Accept connections from clients"
    echo "  2) Client - Connect to a server"
    echo "  3) Exit"
    echo ""
    read -p "Select option [1-3]: " CHOICE

    case $CHOICE in
        1) setup_server ;;
        2) setup_client ;;
        3) echo "Goodbye!"; exit 0 ;;
        *) error "Invalid option"; main ;;
    esac
}

# Run main
main
